import { promises as fs } from "fs";
import path from "path";
import {
  AppSettingsSchema,
  DEFAULT_SETTINGS,
  type AppSettings,
} from "@/lib/settings/schema";

const SETTINGS_PATH = path.join(process.cwd(), "data", "settings.json");
const ENV_LOCAL_PATH = path.join(process.cwd(), ".env.local");

function settingsFromEnv(): AppSettings {
  const key = process.env.LLM_API_KEY || process.env.OPENAI_API_KEY || "";
  const enabledFlag = process.env.LLM_ENABLED;
  const llmEnabled =
    enabledFlag === "true" ||
    enabledFlag === "1" ||
    (enabledFlag !== "false" &&
      enabledFlag !== "0" &&
      Boolean(key || process.env.LLM_BASE_URL));

  return AppSettingsSchema.parse({
    ...DEFAULT_SETTINGS,
    llmEnabled,
    llmApiKey: key,
    llmBaseUrl:
      process.env.LLM_BASE_URL ||
      process.env.OPENAI_BASE_URL ||
      DEFAULT_SETTINGS.llmBaseUrl,
    llmModel:
      process.env.LLM_MODEL ||
      process.env.OPENAI_MODEL ||
      DEFAULT_SETTINGS.llmModel,
    llmTimeoutMs: Number(process.env.LLM_TIMEOUT_MS) || DEFAULT_SETTINGS.llmTimeoutMs,
    llmProvider:
      (process.env.LLM_BASE_URL || "").includes("127.0.0.1") ||
      (process.env.LLM_BASE_URL || "").includes("localhost")
        ? "local"
        : "cloud",
  });
}

export async function readSettings(): Promise<AppSettings> {
  try {
    const raw = await fs.readFile(SETTINGS_PATH, "utf8");
    return AppSettingsSchema.parse({ ...DEFAULT_SETTINGS, ...JSON.parse(raw) });
  } catch {
    // No settings.json yet — mirror existing .env so CLI/API keep working.
    return settingsFromEnv();
  }
}

export async function writeSettings(
  patch: Partial<AppSettings>,
): Promise<AppSettings> {
  const current = await readSettings();
  const next = AppSettingsSchema.parse({
    ...current,
    ...patch,
    updatedAt: new Date().toISOString(),
  });
  await fs.mkdir(path.dirname(SETTINGS_PATH), { recursive: true });
  await fs.writeFile(SETTINGS_PATH, JSON.stringify(next, null, 2), "utf8");
  await syncEnvLocal(next);
  applySettingsToEnv(next);
  return next;
}

/** Push settings into process.env for the current Node process. */
export function applySettingsToEnv(settings: AppSettings): void {
  process.env.LLM_ENABLED = settings.llmEnabled ? "true" : "false";
  process.env.LLM_API_KEY = settings.llmApiKey || "";
  process.env.LLM_BASE_URL = settings.llmBaseUrl || "";
  process.env.LLM_MODEL = settings.llmModel || "";
  process.env.LLM_TIMEOUT_MS = String(settings.llmTimeoutMs);
}

export async function loadAndApplySettings(): Promise<AppSettings> {
  const settings = await readSettings();
  applySettingsToEnv(settings);
  return settings;
}

async function syncEnvLocal(settings: AppSettings): Promise<void> {
  const lines = [
    "# Generated by hk-fin-pulse settings page — do not commit",
    `LLM_ENABLED=${settings.llmEnabled ? "true" : "false"}`,
    `LLM_API_KEY=${escapeEnv(settings.llmApiKey)}`,
    `LLM_BASE_URL=${escapeEnv(settings.llmBaseUrl)}`,
    `LLM_MODEL=${escapeEnv(settings.llmModel)}`,
    `LLM_TIMEOUT_MS=${settings.llmTimeoutMs}`,
    "",
  ];
  await fs.writeFile(ENV_LOCAL_PATH, lines.join("\n"), "utf8");
}

function escapeEnv(value: string): string {
  if (!value) return "";
  if (/[\s#"']/.test(value)) return `"${value.replace(/"/g, '\\"')}"`;
  return value;
}

export function publicSettings(settings: AppSettings) {
  const key = settings.llmApiKey;
  return {
    ...settings,
    llmApiKey: key ? `••••${key.slice(-4)}` : "",
    llmApiKeySet: Boolean(key),
  };
}
